name: Source Code Tests
on: [push]
permissions:
    contents: read
jobs:
    tests:
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install ruff
              run: pip install ruff==0.5.5
            - name: Run ruff
              run: ruff check
            - name: Install locache
              run: pip install ".[tests]"
            - name: Run tests
              run: pytest tests.py --cov locache --cov-report xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
