name: Source Code Tests
on: [push]
permissions:
    contents: read
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
            - name: Install ruff
              run: pip install ruff==0.5.5
            - name: Run ruff
              run: ruff check
            - name: Install locache
              run: pip install -e ".[dev]"
            - name: Run tests
              run: pytest tests.py --cov locache --cov-report xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
